apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: ss-cluster.example.com
  name: nodes-ondemand
spec:
  role: Node
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20231207
  minSize: 3 # Set to a multiple of 3 to start with 1 instance per AZ
  maxSize: 15
  subnets:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  mixedInstancesPolicy:
    instances:
    - m5.large
    - m5a.large
    - m6i.large
    onDemandBase: 0
    onDemandAboveBase: 100
    spotAllocationStrategy: capacity-optimized
